### ISSUE TITLE
Use of undeclared type 'CPMapContentWindow'

### ISSUE THREAD

**Issue by OzBob** [Svantulden/carplay-navigation#1]
On iOS 10.0 beta 4.

Clone
Build
Svantulden/carplay-navigation/CarplayNavigationTesting/AppDelegate.swift:16:20: Use of undeclared type 'CPMapContentWindow'

**Comment by Svantulden** [comment]
Ah, I see that Apple has changed naming from `CPMapContentWindow` to `CPWindow` since XCode beta 4, thanks for mentioning. I've updated the master branch (in commit e594a8756ea6c382fc82dd93abea94d397efcfda) to reflect this change. 

Does this fix the build for you?
